"""Generate results/run_registry.json - audit trail for every number in the
manuscript (git commit, seeds, split-file hashes, method versions).

v33: run AFTER scripts/rerun_v33.py and scripts/run_tcga_cox.py.
"""
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def sha1(p):
    h = hashlib.sha1()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()[:16]


def git_commit():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip()
    except Exception:
        return "n/a (not a git repo or no commit)"


def main():
    splits = sorted((REPO / "data" / "cohorts").glob("*/*/*splits*.json"))
    registry = {
        "generated": "2026-09-02",
        "note": "v33 audit revision. Each manuscript number is regenerated by "
                "scripts in this repository; splits and data files are hashed "
                "so future re-runs can verify bitwise identical inputs.",
        "git_commit": git_commit(),
        "seed_policy": {"cv_folds": 42, "permutation": 42,
                        "mutual_info": 42, "bootstrap_ci": 42,
                        "kfold_seeds": "42..51"},
        "key_scripts": {
            "rerun_v33": "scripts/rerun_v33.py (all benchmark + permutation tables)",
            "run_tcga_cox": "scripts/run_tcga_cox.py (Table S15, BH-adjusted)",
            "hugo_survival_v33": "scripts/hugo_survival_v33.py (Table 9)",
            "rebuild_riaz_recist": "scripts/rebuild_riaz_recist.py (Riaz RECIST n=42)",
        },
        "outputs": {
            "benchmark": "results/benchmark/v33/benchmark_v33.json",
            "permutation": "results/benchmark/v33/permutation_v33.json",
            "kfold": "results/benchmark/v33/riaz_recist_kfold_v33.json",
            "survival": "results/benchmark/v33/hugo_survival_v33.json",
            "tcga": "data/tcga/tcga_cox_all.json",
        },
        "data_hashes": {str(p.relative_to(REPO)): sha1(p) for p in splits},
    }
    out = REPO / "results" / "run_registry.json"
    with open(out, "w") as fh:
        json.dump(registry, fh, indent=1)
    print(f"Wrote {out}")
    print("git commit:", registry["git_commit"])
    print(f"hashed {len(registry['data_hashes'])} split files")


if __name__ == "__main__":
    sys.exit(main())
